#!/usr/bin/env node
/**
 * EmailJS one-time setup for Qinetic contact form.
 *
 * Usage:
 *   node scripts/emailjs-setup.mjs
 *   node scripts/emailjs-setup.mjs <service_id> <template_id> <public_key>
 *
 * Dashboard steps (https://dashboard.emailjs.com/):
 * 1. Sign up / sign in (free)
 * 2. Email Services → Add New Service → Gmail → connect helloparvkothari@gmail.com
 * 3. Email Templates → Create New Template:
 *    - To Email: helloparvkothari@gmail.com
 *    - From Name: Qinetic Contact
 *    - Subject: {{subject}}
 *    - Content:
 *        New message from {{from_name}}
 *
 *        Subject: {{subject}}
 *
 *        {{message}}
 * 4. Account → API Keys → copy Public Key
 * 5. Run this script with the three IDs
 */

import fs from "fs";
import path from "path";
import readline from "readline";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const envPath = path.join(root, ".env");

const TO_EMAIL = "helloparvkothari@gmail.com";

function ask(question) {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

async function testSend(serviceId, templateId, publicKey) {
  const res = await fetch("https://api.emailjs.com/api/v1.0/email/send", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      service_id: serviceId,
      template_id: templateId,
      user_id: publicKey,
      template_params: {
        from_name: "Qinetic Setup Test",
        subject: "EmailJS connected successfully",
        message:
          "If you received this, the Qinetic contact form is ready to use.",
        to_email: TO_EMAIL,
      },
    }),
  });

  const text = await res.text();
  if (!res.ok) {
    throw new Error(`${res.status} ${text}`);
  }
  return text;
}

async function main() {
  let serviceId = process.argv[2];
  let templateId = process.argv[3];
  let publicKey = process.argv[4];

  console.log("\nQinetic — EmailJS setup\n");
  console.log("Recipient:", TO_EMAIL);
  console.log(
    "\nIf you haven't created EmailJS resources yet, open:\n  https://dashboard.emailjs.com/\n"
  );

  if (!serviceId) {
    serviceId = await ask("Service ID (e.g. service_abc123): ");
  }
  if (!templateId) {
    templateId = await ask("Template ID (e.g. template_xyz789): ");
  }
  if (!publicKey) {
    publicKey = await ask("Public Key: ");
  }

  if (!serviceId || !templateId || !publicKey) {
    console.error("\nMissing one or more values. Aborting.");
    process.exit(1);
  }

  const env = `# EmailJS — generated by scripts/emailjs-setup.mjs
VITE_EMAILJS_SERVICE_ID=${serviceId}
VITE_EMAILJS_TEMPLATE_ID=${templateId}
VITE_EMAILJS_PUBLIC_KEY=${publicKey}
`;

  fs.writeFileSync(envPath, env);
  console.log("\nWrote", envPath);

  process.stdout.write("\nSending test email… ");
  try {
    const result = await testSend(serviceId, templateId, publicKey);
    console.log(result.trim() || "OK");
    console.log(`\nDone. Check ${TO_EMAIL} for the test message.`);
    console.log("Restart the dev server if it's running: npm run dev\n");
  } catch (err) {
    console.log("FAILED");
    console.error("\nTest send error:", err.message);
    console.log(
      "\n.env was still written. Common fixes:\n" +
        "  • Connect Gmail under Email Services\n" +
        "  • Set template To Email to helloparvkothari@gmail.com\n" +
        "  • Add localhost to Allowed Origins (Account → Security)\n"
    );
    process.exit(1);
  }
}

main();
